services:
  backend:
    environment:
      ENABLE_LOCAL_DECOYS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  worker:
    environment:
      ENABLE_LOCAL_DECOYS: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
